//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CocoApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Depot
    {
        public int id { get; set; }
        public string name { get; set; }
        public string zone { get; set; }
        public string latitude { get; set; }
        public string longtitude { get; set; }
        public Nullable<int> route { get; set; }
        public Nullable<int> waypoint { get; set; }
        public Nullable<int> code { get; set; }
    }
}
