//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CocoApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public int id { get; set; }
        public Nullable<int> code { get; set; }
        public string license { get; set; }
        public string user { get; set; }
        public string pass { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string zone { get; set; }
        public string fone { get; set; }
    }
}
