//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CocoApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class news
    {
        public int news_id { get; set; }
        public string news_topic { get; set; }
        public string news_details { get; set; }
        public Nullable<System.DateTime> add_date { get; set; }
        public Nullable<int> add_id { get; set; }
    }
}
