//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CocoApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class thai_dbEntities : DbContext
    {
        public thai_dbEntities()
            : base("name=thai_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<news> news { get; set; }
        public virtual DbSet<support> supports { get; set; }
        public virtual DbSet<time> times { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<van> vans { get; set; }
        public virtual DbSet<waypoint> waypoints { get; set; }
    }
}
