//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CocoApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class van
    {
        public int van_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string van_start { get; set; }
        public string van_stop { get; set; }
        public string van_license { get; set; }
        public Nullable<int> van_license_prov { get; set; }
        public byte[] van_type { get; set; }
        public Nullable<decimal> van_free { get; set; }
        public Nullable<int> van_seat { get; set; }
        public string van_driver { get; set; }
        public string van_phone { get; set; }
        public string van_details { get; set; }
        public string van_status { get; set; }
        public string van_comment { get; set; }
        public string van_img { get; set; }
        public Nullable<System.DateTime> add_date { get; set; }
        public int add_id { get; set; }
        public System.DateTime edit_date { get; set; }
    }
}
