//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CocoApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class waypoint
    {
        public int waypoint_id { get; set; }
        public int van_id { get; set; }
        public Nullable<int> waypoint_order { get; set; }
        public string waypoint_lat { get; set; }
        public string waypoint_lng { get; set; }
        public Nullable<System.DateTime> add_date { get; set; }
        public int add_id { get; set; }
    }
}
